# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MySnapKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MySnapKit
  pod 'SnapKit', '~> 5.0.0'
  pod 'DeviceKit', '~> 4.0'
end
